### ISSUE TITLE
_DenseLayer is mistake,i rewrite for you 

### ISSUE THREAD

**Issue by liwanning** [nota-github/PeleeNet_keras#1]
def _DenseLayer(x,num_input_features, growth_rate, bottleneck_width, drop_rate):

    growth_rate = int(growth_rate / 2)
    inter_channel = int(growth_rate  * bottleneck_width / 4) * 4 

    if inter_channel > num_input_features / 2:
        inter_channel = int(num_input_features / 8) * 4
        print('adjust inter_channel to ',inter_channel)

    
    left = Conv2D(inter_channel, (1, 1), padding='same')(x)
    left = BatchNormalization()(x)
    left = Activation('relu')(x)

    left = Conv2D(growth_rate, (3, 3), padding='same')(x)
    left = BatchNormalization()(x)
    left = Activation('relu')(x)
    
    right = Conv2D(inter_channel, (1, 1), padding='same')(x)
    right = BatchNormalization()(x)
    right = Activation('relu')(x)
    
    right = Conv2D(growth_rate, (3, 3), padding='same')(x)
    right = BatchNormalization()(x)
    right = Activation('relu')(x)
    
    right = Conv2D(growth_rate, (3, 3), padding='same')(x)
    right = BatchNormalization()(x)
    right = Activation('relu')(x)
    out = concatenate([left,x,right],axis=3)

    return out

**Comment by bibekkk** [comment]
Thank u!! I will update the code
